//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransCAM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransCAM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1850	55
        ///1851	55.975
        ///1852	56.95
        ///1853	57.925
        ///1854	58.9
        ///1855	59.875
        ///1856	60.85
        ///1857	61.825
        ///1858	62.8
        ///1859	63.775
        ///1860	64.75
        ///1861	65.725
        ///1862	66.7
        ///1863	67.675
        ///1864	68.65
        ///1865	69.625
        ///1866	70.6
        ///1867	71.575
        ///1868	72.55
        ///1869	73.525
        ///1870	74.5
        ///1871	75.475
        ///1872	76.45
        ///1873	77.425
        ///1874	78.4
        ///1875	79.375
        ///1876	80.35
        ///1877	81.325
        ///1878	82.3
        ///1879	83.275
        ///1880	84.25
        ///1881	85.225
        ///1882	86.2
        ///1883	87.175
        ///1884	88.15
        ///1885	89.125
        ///1886	90.1
        ///1887	91.075
        ///1888	92.05
        ///1889	93.025
        ///1890	94
        ///1891	95.4
        ///1892 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CH4_Emissions_Hist {
            get {
                return ResourceManager.GetString("CH4_Emissions_Hist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1850	0
        ///1851	0.01
        ///1852	0.02
        ///1853	0.03
        ///1854	0.04
        ///1855	0.05
        ///1856	0.06
        ///1857	0.07
        ///1858	0.08
        ///1859	0.09
        ///1860	0.1
        ///1861	0.11
        ///1862	0.12
        ///1863	0.13
        ///1864	0.14
        ///1865	0.15
        ///1866	0.16
        ///1867	0.17
        ///1868	0.18
        ///1869	0.19
        ///1870	0.2
        ///1871	0.21
        ///1872	0.22
        ///1873	0.23
        ///1874	0.24
        ///1875	0.25
        ///1876	0.26
        ///1877	0.27
        ///1878	0.28
        ///1879	0.29
        ///1880	0.3
        ///1881	0.31
        ///1882	0.32
        ///1883	0.33
        ///1884	0.34
        ///1885	0.35
        ///1886	0.36
        ///1887	0.37
        ///1888	0.38
        ///1889	0.39
        ///1890	0.4
        ///1891	0.41
        ///1892	0.42
        ///1893	0.43
        ///1894	0.44
        ///1895	0.45
        ///1896	0.46
        ///18 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CO2_Emissions_Hist {
            get {
                return ResourceManager.GetString("CO2_Emissions_Hist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year	WMGHGs	O3	StrH2O	ReflAer	AIE	BC	SnowAlb	StrAer	Solar	LandUse
        ///1880	0	0	0	0	0	0	0	0	0	0
        ///1881	0.014	0.001	0	-0.005	-0.006	0.003	0.001	0.009	0.021	-0.001
        ///1882	0.028	0.001	0	-0.009	-0.013	0.006	0.002	0.023	0.026	-0.002
        ///1883	0.04	0.002	0	-0.014	-0.019	0.01	0.004	-1.088	0.032	-0.002
        ///1884	0.05	0.003	0.001	-0.019	-0.025	0.013	0.005	-3.332	0.013	-0.003
        ///1885	0.06	0.003	0.001	-0.023	-0.032	0.016	0.006	-1.469	-0.011	-0.004
        ///1886	0.072	0.004	0.001	-0.028	-0.038	0.019	0.007	-0.827	-0.043	-0.005
        ///1887	0.078	0.00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GISS_Forcings {
            get {
                return ResourceManager.GetString("GISS_Forcings", resourceCulture);
            }
        }
    }
}
